load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

################################################################################
# rules_js
################################################################################

http_archive(
    name = "aspect_rules_js",
    sha256 = "c4a5766a45dff25b2eb1789d7a2decfda81b281fc88350d24687620c37fefb25",
    strip_prefix = "rules_js-1.14.0",
    url = "https://github.com/aspect-build/rules_js/archive/refs/tags/v1.14.0.tar.gz",
)

http_archive(
    name = "aspect_rules_ts",
    sha256 = "e81f37c4fe014fc83229e619360d51bfd6cb8ac405a7e8018b4a362efa79d000",
    strip_prefix = "rules_ts-1.0.4",
    url = "https://github.com/aspect-build/rules_ts/archive/refs/tags/v1.0.4.tar.gz",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@aspect_rules_ts//ts:repositories.bzl", "rules_ts_dependencies")

rules_ts_dependencies(ts_version_from = "//:package.json")

load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")

# NB: The rules_js nodejs toolchain should be named something other than "nodejs" so its name does
# not conflict with the build_bazel_rules_nodejs toolchain naming and prevent the two toolchains
# from existing side by side.
# TODO(rules_js_migration): rename to standard `nodejs` once rules_nodejs is completely removed
nodejs_register_toolchains(
    name = "nodejs_rules_js",
    node_version = DEFAULT_NODE_VERSION,
)

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock")

# NB: The npm_translate_lock repository is named @npm_rules_js to not conflict with @npm from
# rules_nodejs.
# TODO(rules_js_migration): rename to standard `npm` once rules_nodejs is completely removed
npm_translate_lock(
    name = "npm_rules_js",
    pnpm_lock = "//bazel:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@npm_rules_js//:repositories.bzl", "npm_repositories")

npm_repositories()

################################################################################
# rules_nodejs
################################################################################

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "c911b5bd8aee8b0498cc387cacdb5f917098ce477fb4182db07b0ef8a9e045c0",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.7.1/rules_nodejs-4.7.1.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    # symlink_node_modules must be explicitly disabled in rules_nodejs 4.7.1
    symlink_node_modules = False,
    yarn_lock = "//:yarn.lock",
)
