// @generated by protoc-gen-es v2.0.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file logger/schema/logger.proto (syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from '@bufbuild/protobuf/codegenv1';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file logger/schema/logger.proto.
 */
export declare const file_logger_schema_logger: GenFile;

/**
 * @generated from message LogMessage
 */
export declare type LogMessage = Message<'LogMessage'> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: int64 time = 2;
   */
  time: bigint;
};

/**
 * Describes the message LogMessage.
 * Use `create(LogMessageSchema)` to create a new message.
 */
export declare const LogMessageSchema: GenMessage<LogMessage>;

/**
 * @generated from message Empty
 */
export declare type Empty = Message<'Empty'> & {};

/**
 * Describes the message Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export declare const EmptySchema: GenMessage<Empty>;

/**
 * @generated from service Logger
 */
export declare const Logger: GenService<{
  /**
   * @generated from rpc Logger.SendLogMessage
   */
  sendLogMessage: {
    methodKind: 'unary';
    input: typeof LogMessageSchema;
    output: typeof EmptySchema;
  };
}>;
