load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
    deps = ["//npm_packages:tsconfig"],
)

ts_project(
    name = "tsc",
    srcs = ["src/lib.ts"],
    declaration = True,
    tsconfig = ":tsconfig",
    deps = ["//:node_modules/@types/node"],
)

js_library(
    name = "pkg",
    srcs = ["package.json"],
    visibility = ["//visibility:public"],
    deps = [":tsc"],
)
