workflow:
  rules:
    # Don't create pipelines for tag pushes
    - if: '$CI_COMMIT_BRANCH'

stages:
    - Aspect Workflows

test:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - aspect test --task-key=test-gl -- //...

buildifier:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - aspect buildifier --task-key=buildifier-gl

format:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - aspect format --task-key=format-gl

gazelle:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - aspect gazelle --task-key=gazelle-gl

lint:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - aspect lint --task-key=lint-gl -- //...

delivery:
  variables:
    GIT_DEPTH: 0
    GIT_FETCH_EXTRA_FLAGS: --tags
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  needs:
    - test
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - aspect delivery --task-key=delivery-gl

# TODO: migrate warming to AXL warming task once available
warming:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - /etc/aspect/workflows/bin/gitlab_section_start "workflows_environment" "Workflows environment"
    - /etc/aspect/workflows/bin/configure_workflows_env
    - /etc/aspect/workflows/bin/gitlab_section_end "workflows_environment"
    - /etc/aspect/workflows/bin/gitlab_section_start "agent_health_check" "Agent health check"
    - /etc/aspect/workflows/bin/agent_health_check
    - /etc/aspect/workflows/bin/gitlab_section_end "agent_health_check"
    - /etc/aspect/workflows/bin/gitlab_section_start "warming" "Warming"
    - rosetta run warming
    - /etc/aspect/workflows/bin/gitlab_section_end "warming"
    - /etc/aspect/workflows/bin/gitlab_section_start "archive_warming_tars" "Archive warming tars"
    - /etc/aspect/workflows/bin/warming_archive
    - /etc/aspect/workflows/bin/gitlab_section_end "archive_warming_tars"
