include:
  - component: $CI_SERVER_FQDN/aspect-build/setup-aspect-gitlab-component/setup@2026.26.7

workflow:
  rules:
    # Don't create pipelines for tag pushes
    - if: '$CI_COMMIT_BRANCH'

stages:
    - Aspect Workflows

test:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .setup-aspect
  script:
    - aspect test --task:name=test-gl -- //...

buildifier:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .setup-aspect
  script:
    - aspect buildifier --task:name=buildifier-gl

format:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .setup-aspect
  script:
    - aspect format --task:name=format-gl

gazelle:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .setup-aspect
  script:
    - aspect gazelle --task:name=gazelle-gl

lint:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .setup-aspect
  script:
    - aspect lint --task:name=lint-gl -- //...

delivery:
  variables:
    GIT_DEPTH: 0
    GIT_FETCH_EXTRA_FLAGS: --tags
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  needs:
    - test
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .setup-aspect
  script:
    - aspect delivery --task:name=delivery-gl

warming:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
  extends: .setup-aspect
  script:
    - aspect ci warming --task:name warming -- //...
