include:
  - component: $CI_SERVER_FQDN/aspect-build/aspect-workflows-gitlab-component/setup@2026.25.5

workflow:
  rules:
    # Don't create pipelines for tag pushes
    - if: '$CI_COMMIT_BRANCH'

stages:
    - Aspect Workflows

test:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .aspect-workflows-setup
  script:
    - aspect test --task:name=test-gl -- //...

buildifier:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .aspect-workflows-setup
  script:
    - aspect buildifier --task:name=buildifier-gl

format:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .aspect-workflows-setup
  script:
    - aspect format --task:name=format-gl

gazelle:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .aspect-workflows-setup
  script:
    - aspect gazelle --task:name=gazelle-gl

lint:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .aspect-workflows-setup
  script:
    - aspect lint --task:name=lint-gl -- //...

delivery:
  variables:
    GIT_DEPTH: 0
    GIT_FETCH_EXTRA_FLAGS: --tags
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  needs:
    - test
  rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule"'
  extends: .aspect-workflows-setup
  script:
    - aspect delivery --task:name=delivery-gl

# TODO: migrate warming to AXL warming task once available
warming:
  tags:
    - aspect-workflows
    - aspect-default
  stage: Aspect Workflows
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
  extends: .aspect-workflows-setup
  script:
    # we still need a .aspect/workflows/config.yaml until the AXL warming task is ready
    - /etc/aspect/workflows/bin/gitlab_section_start "legacy_config" "Create legacy workflows config"
    - mkdir -p .aspect/workflows
    - printf 'tasks:\n  - warming:\n' > .aspect/workflows/config.yaml
    - /etc/aspect/workflows/bin/gitlab_section_end "legacy_config"
    - /etc/aspect/workflows/bin/gitlab_section_start "warming" "Warming"
    - rosetta run warming
    - /etc/aspect/workflows/bin/gitlab_section_end "warming"
    - /etc/aspect/workflows/bin/gitlab_section_start "archive_warming_tars" "Archive warming tars"
    - /etc/aspect/workflows/bin/warming_archive
    - /etc/aspect/workflows/bin/gitlab_section_end "archive_warming_tars"
