#! /bin/sh

export RUNFILES_DIR=${RUNFILES_DIR:-"$0.runfiles"}

export PRISMA_QUERY_ENGINE_BINARY="${RUNFILES_DIR}/{{QUERY_ENGINE}}"
export PRISMA_QUERY_ENGINE_LIBRARY="${RUNFILES_DIR}/{{LIBQUERY_ENGINE}}"
export PRISMA_SCHEMA_ENGINE_BINARY="${RUNFILES_DIR}/{{SCHEMA_ENGINE}}"

exec "${RUNFILES_DIR}/{{PRISMA_BIN}}" "$@"
