workspace(name = "oci_python_image")

load(":fetch.bzl", "fetch")

fetch()

load(":configure.bzl", "configure")

configure()

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python39",
    python_version = "3.9",
)

load("@python39//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pypi",
    python_interpreter_target = interpreter,
    requirements_lock = "//:requirements.txt",
)

load("@pypi//:requirements.bzl", "install_deps")

install_deps()

load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "distroless_python",
    digest = "sha256:b48e216f7c4adcf24fecd7016f3b8ead76866a19571819f67f47c1ccaf899717",
    image = "python",
    # image = "gcr.io/distroless/python3",
    # platforms = [
    #     "linux/amd64",
    #     "linux/arm64",
    # ],
)
