version: 2.1

orbs:
  setup-aspect: aspect-build/setup-aspect@2026.26.2

workflows:
  aspect-workflows:
    jobs:
      - test
      - buildifier
      - format
      - gazelle
      - lint
      - delivery:
          requires:
            - test
    when:
      not:
        equal:
        - scheduled_pipeline
        - << pipeline.trigger_source >>
  aspect-workflows-warming:
    jobs:
      - warming
    when:
      and:
        - equal:
          - scheduled_pipeline
          - << pipeline.trigger_source >>
        - equal:
          - aspect-workflows-warming
          - << pipeline.schedule.name >>

jobs:
  test:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - setup-aspect/setup
      - run:
          name: Test
          command: aspect test --task:name=test-cci -- //...

  buildifier:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - setup-aspect/setup
      - run:
          name: Buildifier
          command: aspect buildifier --task:name=buildifier-cci

  format:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - setup-aspect/setup
      - run:
          name: Format
          command: aspect format --task:name=format-cci

  gazelle:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - setup-aspect/setup
      - run:
          name: Gazelle
          command: aspect gazelle --task:name=gazelle-cci

  lint:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - setup-aspect/setup
      - run:
          name: Lint
          command: aspect lint  --task:name=lint-cci -- //...
  
  delivery:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - setup-aspect/setup
      - run:
          name: Delivery
          command: aspect delivery --task:name=delivery-cci

  # TODO: migrate warming to AXL warming task once available
  warming:
    environment:
      ASPECT_WORKFLOWS_CIRCLE_PIPELINE_NUMBER: << pipeline.number >>
      ASPECT_WORKFLOWS_CIRCLE_PIPELINE_PROJECT_TYPE: << pipeline.project.type >>
      ASPECT_WORKFLOWS_CIRCLE_WORKFLOW_BASE_NAME: aspect-workflows
      ASPECT_WORKFLOWS_CONFIG: .aspect/workflows/config.yaml
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - setup-aspect/setup
      # we still need a .aspect/workflows/config.yaml until the AXL warming task is ready
      - run:
          name: Create legacy workflows config
          command: |
            mkdir -p .aspect/workflows
            cat > .aspect/workflows/config.yaml << 'EOF'
            tasks:
              - warming:
            EOF
      - run:
          name: Create warming archive for root
          command: rosetta run warming
      - run:
          name: Archive warming tars
          command: /etc/aspect/workflows/bin/warming_archive
