steps:
- key: test
  label: ":bazel: Test"
  agents:
    queue: aspect-default
  plugins:
    - aspect-build/setup-aspect#63f7af7bde5d378934d54edf0978edc02791375a: ~ # v2026.26.5
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect test --task:name=test-bk -- //...

- key: buildifier
  label: ":hammer_and_wrench: Buildifier"
  agents:
    queue: aspect-default
  plugins:
    - aspect-build/setup-aspect#63f7af7bde5d378934d54edf0978edc02791375a: ~ # v2026.26.5
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect buildifier --task:name buildifier-bk

- key: format
  label: ":hammer_and_wrench: Format"
  agents:
    queue: aspect-default
  plugins:
    - aspect-build/setup-aspect#63f7af7bde5d378934d54edf0978edc02791375a: ~ # v2026.26.5
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect format --task:name=format-bk

- key: gazelle
  label: ":deer: Gazelle"
  agents:
    queue: aspect-default
  plugins:
    - aspect-build/setup-aspect#63f7af7bde5d378934d54edf0978edc02791375a: ~ # v2026.26.5
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect gazelle --task:name=gazelle-bk

- key: lint
  label: ":broom: Lint"
  agents:
    queue: aspect-default
  plugins:
    - aspect-build/setup-aspect#63f7af7bde5d378934d54edf0978edc02791375a: ~ # v2026.26.5
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect lint  --task:name=lint-bk -- //...

- key: delivery
  label: ":bazel: Delivery"
  agents:
    queue: aspect-default
  plugins:
    - aspect-build/setup-aspect#63f7af7bde5d378934d54edf0978edc02791375a: ~ # v2026.26.5
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect delivery --task:name=delivery-bk
  depends_on:
    - test
