steps:
- key: test
  label: ":bazel: Test"
  agents:
    queue: aspect-default
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect test --task-key=test-bk -- //...

- key: buildifier
  label: ":hammer_and_wrench: Buildifier"
  agents:
    queue: aspect-default
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect buildifier --task-key buildifier-bk

- key: format
  label: ":hammer_and_wrench: Format"
  agents:
    queue: aspect-default
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect format --task-key=format-bk

- key: gazelle
  label: ":deer: Gazelle"
  agents:
    queue: aspect-default
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect gazelle --task-key=gazelle-bk

- key: lint
  label: ":broom: Lint"
  agents:
    queue: aspect-default
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect lint  --task-key=lint-bk -- //...

- key: delivery
  label: ":bazel: Delivery"
  agents:
    queue: aspect-default
  retry:
    manual:
      allowed: true
      permit_on_passed: false
    automatic:
    - limit: 1
      exit_status: 36
    - limit: 1
      exit_status: 255
    - limit: 1
      exit_status: -1
  command: aspect delivery --task-key=delivery-bk
  depends_on:
    - test
