// @generated by protoc-gen-es v2.2.0 with parameter "target=js+dts,import_extension=js"
// @generated from file example/v1/example.proto (package example.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file example/v1/example.proto.
 */
export declare const file_example_v1_example: GenFile;

/**
 * @generated from message example.v1.ExampleUser
 */
export declare type ExampleUser = Message<"example.v1.ExampleUser"> & {
  /**
   * Required user ID.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Required email with basic format validation.
   *
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * Required display name; at least 1 character.
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * Non-negative age; optional.
   *
   * @generated from field: int32 age = 4;
   */
  age: number;
};

/**
 * Describes the message example.v1.ExampleUser.
 * Use `create(ExampleUserSchema)` to create a new message.
 */
export declare const ExampleUserSchema: GenMessage<ExampleUser>;

