// @generated by protoc-gen-es v2.10.2 with parameter "target=js+dts,import_extension=js"
// @generated from file example/v1/example.proto (package example.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.js";

/**
 * Describes the file example/v1/example.proto.
 */
export const file_example_v1_example = /*@__PURE__*/
  fileDesc("ChhleGFtcGxlL3YxL2V4YW1wbGUucHJvdG8SCmV4YW1wbGUudjEiewoLRXhhbXBsZVVzZXISFAoCaWQYASABKAlCCLpIBXIDsAEBEhkKBWVtYWlsGAIgASgJQgq6SAfIAQFyAmABEiIKDGRpc3BsYXlfbmFtZRgDIAEoCUIMukgJyAEBcgQQARhkEhcKA2FnZRgEIAEoBUIKukgHGgUYlgEoAELAAQoOY29tLmV4YW1wbGUudjFCDEV4YW1wbGVQcm90b1ABWldnaXRodWIuY29tL2FzcGVjdC1idWlsZC9iYXplbC1leGFtcGxlcy9wcm90by1idWYtZ28tdHMvZ28vZ2VucHJvdG8vZXhhbXBsZS92MTtleGFtcGxldjGiAgNFWFiqAgpFeGFtcGxlLlYxygIKRXhhbXBsZVxWMeICFkV4YW1wbGVcVjFcR1BCTWV0YWRhdGHqAgtFeGFtcGxlOjpWMWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * Describes the message example.v1.ExampleUser.
 * Use `create(ExampleUserSchema)` to create a new message.
 */
export const ExampleUserSchema = /*@__PURE__*/
  messageDesc(file_example_v1_example, 0);

