// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: write_source_files/bar/baz.proto

package bar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Baz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Baz           *string                `protobuf:"bytes,1,req,name=baz" json:"baz,omitempty"`
	Id            *int32                 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Baz) Reset() {
	*x = Baz{}
	mi := &file_write_source_files_bar_baz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Baz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Baz) ProtoMessage() {}

func (x *Baz) ProtoReflect() protoreflect.Message {
	mi := &file_write_source_files_bar_baz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Baz.ProtoReflect.Descriptor instead.
func (*Baz) Descriptor() ([]byte, []int) {
	return file_write_source_files_bar_baz_proto_rawDescGZIP(), []int{0}
}

func (x *Baz) GetBaz() string {
	if x != nil && x.Baz != nil {
		return *x.Baz
	}
	return ""
}

func (x *Baz) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

var File_write_source_files_bar_baz_proto protoreflect.FileDescriptor

const file_write_source_files_bar_baz_proto_rawDesc = "" +
	"\n" +
	" write_source_files/bar/baz.proto\x12\x03bar\"'\n" +
	"\x03Baz\x12\x10\n" +
	"\x03baz\x18\x01 \x02(\tR\x03baz\x12\x0e\n" +
	"\x02id\x18\x02 \x02(\x05R\x02id"

var (
	file_write_source_files_bar_baz_proto_rawDescOnce sync.Once
	file_write_source_files_bar_baz_proto_rawDescData []byte
)

func file_write_source_files_bar_baz_proto_rawDescGZIP() []byte {
	file_write_source_files_bar_baz_proto_rawDescOnce.Do(func() {
		file_write_source_files_bar_baz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_write_source_files_bar_baz_proto_rawDesc), len(file_write_source_files_bar_baz_proto_rawDesc)))
	})
	return file_write_source_files_bar_baz_proto_rawDescData
}

var file_write_source_files_bar_baz_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_write_source_files_bar_baz_proto_goTypes = []any{
	(*Baz)(nil), // 0: bar.Baz
}
var file_write_source_files_bar_baz_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_write_source_files_bar_baz_proto_init() }
func file_write_source_files_bar_baz_proto_init() {
	if File_write_source_files_bar_baz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_write_source_files_bar_baz_proto_rawDesc), len(file_write_source_files_bar_baz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_write_source_files_bar_baz_proto_goTypes,
		DependencyIndexes: file_write_source_files_bar_baz_proto_depIdxs,
		MessageInfos:      file_write_source_files_bar_baz_proto_msgTypes,
	}.Build()
	File_write_source_files_bar_baz_proto = out.File
	file_write_source_files_bar_baz_proto_goTypes = nil
	file_write_source_files_bar_baz_proto_depIdxs = nil
}
