# We maintain mirrors of this repo for demonstrating Aspect Workflows on other CI platforms.
# When commits land there, we sync them to mirrors in this workflow.
name: Sync Mirrors
on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['*']
jobs:
  push-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Get a full history so all commits are present
        uses: actions/checkout@v4
        with:
            path: fresh-clone
            fetch-depth: 0
      - working-directory: fresh-clone
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
            eval $(ssh-agent -s)
            ssh-add - <<< '${{ secrets.GITLAB_BAZEL_EXAMPLES_DEPLOY_KEY }}'
            git push git@gitlab.com:aspect-build/bazel-examples.git HEAD:main
            git push --tags git@gitlab.com:aspect-build/bazel-examples.git
