name: Aspect Workflows Warming

on:
    # Run the workflows on a cron schedule to periodically create an up-to-date warming archive
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    schedule:
        - cron: '0 8 * * *'

    # Allow this to be triggered manually via the GitHub UI Actions tab
    workflow_dispatch:

jobs:
    warming-archive:
        name: Aspect Workflows Warming
        runs-on: [self-hosted, aspect-workflows, aspect-default]
        steps:
            - uses: actions/checkout@v6
            - uses: aspect-build/setup-aspect@8689a6ee13d15bbde12e55632330595076ecabf9 # v2026.26.8
            - name: Warming
              run: aspect ci warming --task:name warming -- //...
