name: Aspect Workflows Warming

on:
    # Run the workflows on a cron schedule to periodically create an up-to-date warming archive
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    schedule:
        - cron: '0 8 * * *'

    # Allow this to be triggered manually via the GitHub UI Actions tab
    workflow_dispatch:

# TODO: migrate warming to AXL warming task once available
jobs:
    warming-archive:
        name: Aspect Workflows Warming
        runs-on: [self-hosted, aspect-workflows, aspect-default]
        steps:
            - uses: actions/checkout@v6
            - uses: aspect-build/setup-aspect@b7443e6f0b4a72507d73fcc49c16eecaf28786f9 # v2026.26.7
            # we still need a .aspect/workflows/config.yaml until the AXL warming task is ready
            - name: Create legacy workflows config
              run: |
                mkdir -p .aspect/workflows
                cat > .aspect/workflows/config.yaml << 'EOF'
                tasks:
                  - warming:
                EOF
            - name: Create warming archive
              run: rosetta run warming
            - name: Archive warming tars
              run: /etc/aspect/workflows/bin/warming_archive
